### PR TITLE
Inno Setup Installer Script

### PR DESCRIPTION
**Pull request by rossknudsen**
Round 2 - Fight!

So I have taken on board the comments from the previous Pull Request and revised my submission.  I removed the existing installer projects and added a script to build a single installer using Inno Setup.

To test:
- You will need to build the Debug build as this is what the installer builds from.  The output path is hard-coded into the script but could easily be moved to point at a Release build if so desired.  Note that the post build events from the Debug build may interfere with installation, I'm not sure on this and would be keen for dialogue on this issue.
- You will also need to install Inno Setup and/or Inno Script Studio.  The latter is much better for working on scripts as there are a lot of GUIs to help.
- Once completing the above steps you should be able to compile the installer from Inno Script Studio.

I suggest that you pull my branch and test it thoroughly before committing to replacing the current installers.

### CODE REVIEW

**Comment by rossknudsen** [comment]
Just thinking out loud, do you guys want to have the project installable as a MSI?  MSIs allow people to install software easily via Active Directory.  It looks like Wix allows proper MSIs to be built while Inno Setup exes cannot be turned into MSIs (easily at least).  So either we scrap this idea, or use it in the short term with the possibility of switching to Wix in the future.

**Comment by retailcoder** [comment]
Perhaps we can switch to WIX eventually.. but for now as long as we ditch the InstallShield LE installers...


Sent from Samsung Mobile

**Comment by ckuhn203** [comment]
I left a number of comments on the commit. I have a few concerns yet. 
https://github.com/rossknudsen/Rubberduck/commit/9422638b169e7a80705d6a3a99485484fa23b58c#commitcomment-11002609

**Comment by retailcoder** [comment]
> **Running 32-bit and 64-bit versions of Office on the same computer isn’t supported**

https://technet.microsoft.com/en-us/library/ee681792.aspx

**Comment by ckuhn203** [comment]
Well, ok then. That's inconsistent with the advice I read about registering add-ins. (No. I don't have the link handy. =)

**Pull request merged**
