### PR TITLE
Inno

### PR DESCRIPTION
**Pull request by rossknudsen**
Hey guys,

Here is my attempt at switching the installer from the current to Inno Setup.  I'm not entirely happy with the way it works (which we can discuss on the forums) but its worth a look.

I also changed it so that building the application now uses a common directory.  Not sure if this has broken the unit tests (I forget how to set that up correctly).

I just tried creating the installer and it seems to have worked.  Let me know what you think.

### CODE REVIEW

**Comment by ckuhn203** [comment]
I'll definitely look into this as soon as I have a chance. It will probably be about a week before I can test though. I'm traveling atm. 

What in particular did you have concerns about?

(Very excited to see this PR btw.)

**Comment by retailcoder** [comment]
Is there a UI when the installer runs? If so, can it be configured? Not a showstopper at all, just wondering..

**Comment by rossknudsen** [comment]
Hey all, yes you've raised many points I had thought about but forgot to actually mention.
- The installer *only* checks for Excel.  I basically was too lazy to modify the function to check each of the other office applications.  Which wouldn't actually be too hard, the other reg keys are in the same 'folder'.
- If you want to keep the same output dirs then I don't think that will be a problem.  You do save copying dlls from one project to another which slightly speeds up the build process.  Not much for a two project solution though.
- The existing installers need admin privileges as the default install location is the program files dir.
- The `\rubberduck\rubberduck` folder is a bit over the top.  I noticed it when I was testing the installer and actually removed the second rubberduck.  Its not hard to change that.
- Yes the installer produces a GUI installer very similar to the current one.  So you can change some of the settings.

After sleeping on it last night, I think that it would be better to split the installer into two.  One for each architecture as you currently have.  For one, you can use the same GUIDs that are used in the existing installers.  Two, it will simplify the scripts since all the conditional stuff can go away.  Lastly *if* it is possible to have both architectures installed at the same time, it should allow both installers to run since they can install to different folders and use different registry keys.  Except for the COM visible components.  To solve that problem I think we should use conditional compilation to change the GUIDs for each architecture and actually build the dlls for each type explicitly.

Note: I'm not expecting you to merge this as is.  I'm definitely happy to make further modifications.

**Comment by retailcoder** [comment]
You can't have both 32 and 64 bit Office installed on the same machine.

**Comment by retailcoder** [comment]
Also the current installers require admin privs because they're registering keys to HKLM; I thought we might as well install under `%ProgramFiles%` since we need admin privs anyway.

**Comment by rossknudsen** [comment]
Yeah I thought that was the case, its good to rule that out then.  Ignore comments regarding changing the GUIDs for the application.  However I still think that the script should be split.

The other reason is because then you can easily install to the correct program files directory as well.  I don't think there is a satisfactory way to do that in Inno Setup otherwise.  Which is why I moved the default install location.

**Comment by retailcoder** [comment]
if it's possible to have one download for both 32 and 64 bit Office, I'd go with that, be it just to eliminate the need for users to pick the correct download, especially with users running 32-bit Office on a x64 system.

**Pull request closed without merging**
